'use client';

import { createContext, useContext, useState, ReactNode, useCallback, useMemo, useEffect } from 'react';

type Language = 'sq' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.materials': 'Materials',
    'nav.tests': 'Tests',
    'nav.decisionTrainer': 'Decision Trainer',
    'nav.pricing': 'Pricing',
    'nav.account': 'Account',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.getStarted': 'Get Started',
    'nav.language': 'Language',
    
    // Home Page
    'home.hero.badge': "Kosovo's #1 Driving Theory Platform",
    'home.hero.title': 'Master Your',
    'home.hero.titleAccent': 'Driving Theory Exam',
    'home.hero.description': 'Practice with comprehensive mock tests, track your progress, and pass your exam with confidence. Available in Albanian and English.',
    'home.hero.startLearning': 'Start Learning Free',
    'home.hero.browseCategories': 'Browse Categories',
    'home.hero.mobileComingSoon': 'Mobile version coming soon on Android and iOS.',
    'home.hero.mobileBadge': 'Coming soon',
    'home.hero.appStoreCta': 'Download on the App Store',
    'home.hero.playStoreCta': 'Get it on Google Play',
    'home.hero.newHereTitle': 'New here? Start with a free test and one Study Material chapter.',
    'home.hero.newHereCtaCategory': 'Start Category B test',
    'home.hero.newHereCtaMaterials': 'Open Study Material',
    'home.benefit.badge': 'Practice for the real Kosovo exam',
    'home.benefit.title': 'Clear steps from first test to exam day.',
    'home.benefit.body': 'Mock tests, review tools and Study Material work together so you always know what to do next.',
    'home.trust.badge': 'What you get with DriveWise',
    'home.trust.title': 'Everything you unlock when you join.',
    'home.trust.body': 'You get realistic mock tests, Decision Trainer scenarios, Study Material and a personal dashboard that saves your progress securely to your account.',
    'home.pillars.badge': 'Three tools that work together',
    'home.pillars.title': 'Practice, learn from mistakes, then fix them.',
    'home.pillars.body': 'Mock tests show your level, Decision Trainer trains your decisions, and analytics point you to the right chapters to study.',
    'trainer.heroExplainer': 'Short scenario questions that train your decisions. Sometimes more than one answer can be correct.',
    'pricing.currentPlanFor': 'Current plan for',
    'pricing.until': '· until',
    'plans.hero.badge': 'Smart plans for serious learners',
    'plans.hero.title': 'Choose your plan',
    'plans.hero.subtitle':
      'Start free with a few tests, then unlock Decision Trainer, full Study Material, and detailed reviews when you are ready.',
    'plans.profilePaidPlansTitle': 'Your paid plans',
    'plans.profileExtendViaPricingCta': 'Go to pricing',
    
    // Features
    'features.comprehensive.title': 'Comprehensive Tests',
    'features.comprehensive.desc': '10 mock tests per category with real exam-style questions',
    'features.progress.title': 'Track Progress',
    'features.progress.desc': 'Advanced analytics and insights to monitor your improvement',
    'features.guaranteed.title': 'Pass Guaranteed',
    'features.guaranteed.desc': 'Proven methods to help you pass on your first attempt',
    
    // Categories
    'categories.title': 'Choose Your License Category',
    'categories.description': 'Select your license type and start practicing with our comprehensive mock tests',
    'categories.startPractice': 'Start Practice',
    
    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInDescription': 'Sign in to continue your driving theory practice',
    'auth.createAccount': 'Create Account',
    'auth.createAccountDescription': 'Start your journey to passing the driving theory exam',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Create Account',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.backToHome': 'Back to home',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.logoutSuccess': 'You have been logged out successfully.',
    'auth.logoutError': 'Error while logging out.',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Track your progress and continue learning',
    'dashboard.totalTests': 'Total Tests',
    'dashboard.avgScore': 'Avg Score',
    'dashboard.bestScore': 'Best Score',
    'dashboard.streak': 'Streak',
    'dashboard.thisWeek': 'this week',
    'dashboard.lastWeek': 'last week',
    'dashboard.personalBest': 'Personal best',
    'dashboard.keepGoing': 'Keep going!',
    'dashboard.streakSubtitle': 'Global streak across tests and Decision Trainer.',
    'dashboard.days': 'days',
    'dashboard.weeklyProgress': 'Weekly Progress',
    'dashboard.weeklyProgressDesc': 'Test scores over the past week',
    'dashboard.passRate': 'Pass Rate',
    'dashboard.passRateDesc': 'Overall performance',
    'dashboard.categoryPerformance': 'Category Performance',
    'dashboard.categoryPerformanceDesc': 'Tests per category',
    'dashboard.recentTests': 'Recent Tests',
    'dashboard.recentTestsDesc': 'Latest attempts',
    'dashboard.continuelearning': 'Continue Learning',
    'dashboard.pickUpWhere': 'Pick up where you left off',
    'dashboard.continueCategoryB': 'Continue Category B',
    'dashboard.browseCategories': 'Browse Categories',
    'dashboard.startNewCategory': 'Start New Category',
    'dashboard.passed': 'Passed',
    'dashboard.failed': 'Failed',
    'dashboard.weakTopicsTitle': 'Your weakest topics',
    'dashboard.weakTopicsSubtitle': 'These are the topics you most often miss across all tests.',
    'dashboard.testAchievementsTitle': 'Test achievements',
    'dashboard.testAchievementsSubtitle': 'Small milestones to keep you motivated while practicing mock tests.',
    'dashboard.trainerProgressTitle': 'Decision Trainer Progress',
    'dashboard.trainerAchievementsLabel': 'Achievements:',
    'dashboard.trainerScenarios': 'scenarios',
    'dashboard.trainerAccuracy': 'accuracy',
    'dashboard.trainerXp': 'XP',
    'dashboard.trainerBestStreak': 'Best streak',
    'dashboard.trainerCategoriesPracticed': 'Categories practiced',
    'dashboard.testHistoryTitle': 'Test History',
    'dashboard.testHistorySubtitle': 'View all your completed tests and review your answers',
    'dashboard.viewHistoryCta': 'View History',
    'dashboard.avgScoreHighSubtitle': 'Great job!',
    'dashboard.avgScoreLowSubtitle': 'Keep practicing',
    'profile.title': 'Plan & usage summary',
    'profile.adminUnlimited': 'Admin: You already have unlimited access to all categories and features.',
    'profile.premiumBadge': 'Active paid plan',
    'profile.planStatusTitle': 'Plans & usage by license category',
    'profile.expiresOnLabel': 'Expires on:',
    'profile.daysRemaining': 'days left',
    'profile.freeUsageLabel': 'Free usage this cycle:',
    'profile.testsLabel': 'tests',
    'profile.upgradeCta': 'Start plan',
    'profile.extendCta': 'Extend / renew',
    'profile.previewCta': 'Manage users',
    'profile.accountSettingsTitle': 'Account settings',
    'profile.accountSettingsDescription': 'Update your display name and see which email is used for your DriveWise account.',
    'profile.displayNameLabel': 'Display name',
    'profile.emailLabel': 'Email',
    'profile.emailHelp': 'This email is used to sign in and receive important account notices.',
    'profile.dangerZoneTitle': 'Danger zone',
    'profile.dangerZoneDescription': 'Permanently delete your account and all associated test history, trainer progress, and plans.',
    'profile.deleteAccountButton': 'Delete account',
    'profile.deleteDialogTitle': 'Delete account',
    'profile.deleteDialogDescription': 'This action cannot be undone. This will permanently delete your DriveWise account and remove all of your data, including test history, Decision Trainer progress, and any active or past plans.',
    'profile.deleteDialogConfirmLabel': 'Type DELETE in all caps to confirm:',
    'profile.deleteDialogCancel': 'Cancel',
    'profile.deleteDialogConfirm': 'Delete my account',
    'profile.deleteDialogConfirming': 'Deleting...',

    // Dashboard Onboarding / Learning Path (English)
    'dashboard.onboardingTitle': 'Start your learning journey',
    'dashboard.onboardingSubtitle': 'Follow these three steps to prepare for your theory exam.',
    'dashboard.onboardingStep1': '1. Read the study materials for your next chapter.',
    'dashboard.onboardingStep2': '2. Practice real situations in Decision Trainer.',
    'dashboard.onboardingStep3': '3. Test yourself with full mock tests.',
    
    // Decision Trainer Page (English)
    'trainer.title': 'Decision Trainer',
    'trainer.practiceModes': 'Practice modes',
    'trainer.fullCategory': 'Full category',
    'trainer.quick5': 'Quick: 5 questions',
    'trainer.quick10': 'Quick: 10 questions',
    'trainer.weakPoints': 'Weak points',
    'trainer.statusNew': 'New',
    'trainer.statusStrong': 'Strong',
    'trainer.statusImproving': 'Improving',
    'trainer.statusNeedsAttention': 'Needs attention',
    'trainer.lastSessionTitle': 'Last session',
    'trainer.questionsToReview': 'Questions to review:',
    'trainer.perfectSession': 'Perfect session! No mistakes to review.',
    'trainer.practiceAgain5': 'Practice this category again (5 questions)',
    'trainer.leaderboard': 'Leaderboard',
    'trainer.toastTimesUp': "Time's up!",
    'trainer.toastCorrect': 'Correct!',
    'trainer.toastIncorrect': 'Incorrect. Read the explanation to learn!',
    'trainer.toastWeakLocked': 'Complete at least one category first to unlock weak points mode.',
    'trainer.toastFocusingWeak': 'Focusing on your weakest category:',
    'trainer.toastSyncFailed': 'Results saved locally but failed to sync to leaderboard.',
    'trainer.modeFull': 'Full category',
    'trainer.modeQuick5': 'Quick: 5 questions',
    'trainer.modeQuick10': 'Quick: 10 questions',
    'trainer.modeWeak': 'Weak points (5 questions)',
    'trainer.scenariosShort': 'scenarios',
    'trainer.accuracyShort': 'accuracy',

    // Category Page
    'category.licenseCategory': 'License Category',
    'category.mockTests': 'Mock Tests',
    'category.minutesEach': 'minutes each',
    'category.selectTest': 'Select Your Test',
    'category.selectTestDesc': 'Choose from 10 comprehensive mock tests',
    'category.questions': 'Questions',
    'category.start': 'Start',
    'category.noTestsTitle': 'No tests available yet',
    'category.noTestsDescription': 'Your instructor or admin has not added mock tests for this category yet.',
    
    // Test Page
    'test.exitTest': 'Exit Test',
    'test.question': 'Question',
    'test.of': 'of',
    'test.backToTests': 'Back to Tests',
    'test.congratulations': 'Congratulations!',
    'test.keepPracticing': 'Keep Practicing!',
    'test.test': 'Test',
    'test.correctAnswers': 'correct answers',
    'test.passingScore': 'Passing Score',
    'test.passed': 'Passed',
    'test.failed': 'Failed',
    'test.retakeTest': 'Retake Test',
    'test.viewAllTests': 'View All Tests',
    'test.loadingQuestions': 'Loading test questions...',
    'test.noQuestionsTitle': 'No Questions Available',
    'test.noQuestionsDescription': 'There are no questions available for this test yet.',
    'test.sessionStats': 'Session Stats',
    'test.correctLabel': 'Correct',
    'test.accuracy': 'Accuracy',
    'test.bestStreak': 'Best Streak',
    'test.selectAnswers': 'Select one or more answers',
    'test.optionsSelected': 'options selected',
    'test.mixedName': 'Mixed Question Test',
    'test.personalizedName': 'Personalized Test',
    'test.previous': 'Previous',
    'test.next': 'Next',
    'test.submitTest': 'Submit Test',
    'test.submitAnswer': 'Submit Answer',
    'test.timeLeft': 'Time Left',
    'test.questionImage': 'Question Image',
    'test.questionIllustration': 'Question illustration',
    'test.answeredLabel': 'answered',
    'test.correctTitle': '✓ Correct!',
    'test.incorrectTitle': '✗ Incorrect - Learn from this!',
    'test.nextStepsTitle': 'What should you do next?',
    'test.nextStepsPassedStandard': 'Great work! Next, try a Mixed test or continue in Decision Trainer to deepen your understanding.',
    'test.nextStepsPassedMixedOrPersonalized': 'Great work! You can keep building confidence with more tests in this category or continue in Decision Trainer.',
    'test.nextStepsFailedPersonalized': 'Review this personalized test to understand your mistakes, then continue focusing on weak points in Decision Trainer.',
    'test.nextStepsFailedStandard': 'Review this test in detail to understand your mistakes, then try a Personalized test and Decision Trainer to focus on weak points.',
    'test.practiceWeakPointsCta': 'Practice your weak points',
    'test.mixedTestCta': 'Mixed test for this category',
    'test.decisionTrainerCta': 'Decision Trainer',
    'test.weakTopicsInThisTest': 'Weak topics in this test',

    // Materials Page (English)
    'materials.title': 'Study Materials',
    'materials.subtitle': 'Learn the driving theory step by step',
    'materials.searchPlaceholder': 'Search in this chapter...',
    'materials.section.1': '1. Basic Traffic Rules',
    'materials.section.2': '2. Entering Traffic & Positioning',
    'materials.section.3': '3. Speed Rules',
    'materials.section.4': '4. Turning Rules',
    'materials.section.5': '5. Intersections',
    'materials.section.6': '6. Roundabouts',
    'materials.section.7': '7. Pedestrians & Cyclists',
    'materials.section.8': '8. Meeting Traffic',
    'materials.section.9': '9. Overtaking',
    'materials.section.10': '10. Passing Obstacles',
    'materials.section.11': '11. Warning Signals',
    'materials.section.12': '12. Stopping & Parking',
    'materials.section.13': '13. Breakdowns',
    'materials.readCarefully': 'Read carefully and connect these rules with real driving situations.',
    'materials.noResults': 'No results match your search in this chapter.',
    'materials.emptyTitle': 'No study materials yet',
    'materials.emptySubtitle': 'Your instructor or admin has not added study materials for this course yet.',
    'materials.resultsForPrefix': 'Showing results for',
    'materials.resultsForSuffix': 'in this chapter',
    'materials.errorLoadFailed': 'Failed to load materials',
    'materials.premiumRequiredTitle': 'Unlock full Study Materials access',
    'materials.premiumRequiredDescription': 'Study Material is part of the paid plan. With any active paid plan you get full access to all chapters, explanations, and images.',
    'materials.premiumBenefitAllChapters': 'Access every chapter and topic explanation.',
    'materials.premiumBenefitDeeper': 'Understand why answers are correct so mock tests feel easier.',
    'materials.premiumBenefitVisuals': 'See all reference images and diagrams to memorize faster.',
    'materials.premiumUpgradeCta': 'See plans',

    // History / Review Page (English)
    'history.reviewSubtitle': 'Review your answers and learn from mistakes',
    'history.topicsTitle': 'Topics in this test',
    'history.topicsSubtitle': 'See where you are strong and where you should focus next.',
    'history.weakTopicsPrefix': 'Weak topics:',
    'history.explanationTitle': 'Explanation',
    'history.notFoundTitle': 'Test not found',
    'history.notFoundDescription': 'This test could not be found or has been deleted.',
    'history.missingQuestionTitle': 'Question data not found',
    'history.backToHistory': 'Back to history',

    // Error Page (English)
    'error.title': 'Oops! Something went wrong',
    'error.message': "We encountered an unexpected error. It's not your fault and your data is safe. Please try again or return to the dashboard.",
    'error.tryAgain': 'Try Again',
    'error.goToDashboard': 'Go to Dashboard',
    'error.needHelp': 'Need help?',
    'error.contactSupport': 'If this problem keeps happening, please contact support with the time of this error.',

    // Achievements (English)
    'achievements.firstTestTitle': 'First test completed',
    'achievements.firstTestDesc': 'Complete your first theory mock test.',
    'achievements.fivePassesRowTitle': 'On a roll',
    'achievements.fivePassesRowDesc': 'Pass 5 theory tests in a row with at least 80% score.',
    'achievements.hundredQuestionsTitle': '100 questions answered',
    'achievements.hundredQuestionsDesc': 'Answer at least 100 theory questions across all tests.',

    // Decision Trainer Next Steps (English)
    'trainer.nextStepsTitle': 'What should you do next?',
    'trainer.nextStepsHigh': 'Great accuracy in this category. You can challenge yourself with a full mock test or a mixed test next.',
    'trainer.nextStepsMedium': 'Good progress, but there is still room to improve. Practice a few more scenarios and then try a mock test in this category.',
    'trainer.nextStepsLow': 'Focus on understanding the explanations and review the related chapters, then continue practicing in Decision Trainer before taking a full mock test.',
    'trainer.goToTestsCta': 'Go to tests for this category',
    'trainer.practiceMoreCta': 'Practice more scenarios',
    'trainer.weakPointsModeCta': 'Focus on weak points',
    'trainer.reviewMaterialsCta': 'Review related materials',
    'trainer.firstSteps': 'First Steps',
    'trainer.accuracyAce': 'Accuracy Ace',
    'trainer.streakMaster': 'Streak Master',
    'trainer.xpHunter': 'XP Hunter',
    'trainer.categoryExplorer': 'Category Explorer',
    'trainer.noScenariosTitle': 'No scenarios available yet',
    'trainer.noScenariosSubtitle': 'Ask your instructor or admin to add Decision Trainer scenarios for you.',
    'trainer.firstScenarioDesc': 'Complete your first Decision Trainer scenario.',
    'trainer.accuracyAceDesc': 'Reach 80%+ accuracy over at least 20 attempts.',
    'trainer.streakMasterDesc': 'Hit a best streak of 10 correct answers.',
    'trainer.xpHunterDesc': 'Earn a total of 500 XP in Decision Trainer.',
    'trainer.categoryExplorerDesc': 'Practice at least 3 different Decision Trainer categories.',
    'trainer.consistencyPro': 'Consistency Pro',
    'trainer.consistencyProDesc': 'Complete at least 50 Decision Trainer scenarios across all categories.',
    'trainer.achievementsUnlockedLabel': 'unlocked',
    'trainer.correctCombinationLabel': 'Correct combination:',
    'trainer.yourSelectionLabel': 'Your selection:',
    'trainer.noSelectionLabel': 'No options selected',
    'trainer.reviewChapterCta': 'Review chapter',
    'trainer.premiumRequiredTitle': 'Unlock Decision Trainer',
    'trainer.premiumRequiredDescription': 'Decision Trainer is part of the paid plan. With any active plan you get full access to all scenarios, smarter practice modes, and detailed reviews.',
    'trainer.premiumBenefitUnlimited': 'Unlimited Decision Trainer practice across all categories.',
    'trainer.premiumBenefitStudy': 'Connect scenarios with matching study chapters and test reviews.',
    'trainer.premiumBenefitFocus': 'Smart modes that focus on your weak points and timing.',
    'trainer.premiumUpgradeCta': 'See plans',
    
    // Leaderboard (English)
    'leaderboard.backToTrainer': 'Back to Trainer',
    'leaderboard.subtitle': 'Top learners in Decision Trainer',
    'leaderboard.noDataTitle': 'No leaderboard data yet',
    'leaderboard.noDataSubtitle': 'Complete some scenarios in Decision Trainer to appear on the leaderboard!',
    'leaderboard.startLearningCta': 'Start learning',
    'leaderboard.top10Title': 'Top 10 Leaderboard',
    'leaderboard.showingTop10Of': 'Showing top 10 of',
    'leaderboard.highestXp': 'Highest XP',
    'leaderboard.topAccuracy': 'Top accuracy',
    'leaderboard.longestStreak': 'Longest streak',
    'leaderboard.yourRank': 'Your rank',
  },
  sq: {
    // Navigation
    'nav.home': 'Ballina',
    'nav.dashboard': 'Paneli',
    'nav.materials': 'Materiale',
    'nav.tests': 'Testet',
    'nav.decisionTrainer': 'Decision Trainer',
    'nav.pricing': 'Çmimet',
    'nav.account': 'Llogaria',
    'nav.admin': 'Admin',
    'nav.login': 'Hyrje',
    'nav.logout': 'Dalje',
    'nav.getStarted': 'Fillo Tani',
    'nav.language': 'Gjuha',
    
    // Home Page
    'home.hero.badge': 'Platforma #1 e Teorisë së Drejtimit në Kosovë',
    'home.hero.title': 'Zotëro',
    'home.hero.titleAccent': 'Provimin e Teorisë së Drejtimit',
    'home.hero.description': 'Praktiko me teste provuese të plota, gjurmo përparimin tënd dhe kalo provimin me vetëbesim. Në gjuhën shqipe dhe angleze.',
    'home.hero.startLearning': 'Fillo Mësimin Falas',
    'home.hero.browseCategories': 'Shfleto Kategoritë',
    'home.hero.mobileComingSoon': 'Versioni mobil së shpejti në Android dhe iOS.',
    'home.hero.mobileBadge': 'Së shpejti',
    'home.hero.appStoreCta': 'Shkarko në App Store',
    'home.hero.playStoreCta': 'Merr në Google Play',
    'home.hero.newHereTitle': 'I ri këtu? Fillo me një test falas dhe një kapitull Materiale Mësimore.',
    'home.hero.newHereCtaCategory': 'Fillo testin e Kategorisë B',
    'home.hero.newHereCtaMaterials': 'Hap Materialet Mësimore',
    'home.benefit.badge': 'Praktikë për provimin real në Kosovë',
    'home.benefit.title': 'Hapa të qartë nga testi i parë deri në ditën e provimit.',
    'home.benefit.body': 'Testet provuese, rishikimi dhe Materialet Mësimore punojnë bashkë që të dish gjithmonë çfarë të bësh më pas.',
    'home.trust.badge': 'Çfarë merr me DriveWise',
    'home.trust.title': 'Çfarë zhbllokon sapo të bashkohesh.',
    'home.trust.body': 'Merr teste provuese reale, Decision Trainer, Materiale Mësimore dhe një panel personal ku ruhet sigurt i gjithë progresi yt.',
    'home.pillars.badge': 'Tre mjete që punojnë bashkë',
    'home.pillars.title': 'Praktiko, mëso nga gabimet dhe rregullo ato.',
    'home.pillars.body': 'Testet provuese tregojnë nivelin, Decision Trainer stërvit vendimet dhe analitika të dërgon te kapitujt e duhur për të mësuar.',
    'trainer.heroExplainer': 'Pyetje të shkurtra skenari që stërvisin vendimet e tua. Ndonjëherë më shumë se një përgjigje mund të jetë e saktë.',
    'pricing.currentPlanFor': 'Plani aktual për',
    'pricing.until': '· deri më',
    'plans.hero.badge': 'Plane të zgjuara për nxënës seriozë',
    'plans.hero.title': 'Zgjidh planin tënd',
    'plans.hero.subtitle':
      'Fillo falas me disa teste, pastaj zhblloko Decision Trainer, materialet e plota mësimore dhe rishikimin e detajuar kur të jesh gati.',
    'plans.profilePaidPlansTitle': 'Planet e tua të paguara',
    'plans.profileExtendViaPricingCta': 'Shko te planet',
    
    // Features
    'features.comprehensive.title': 'Teste Gjithëpërfshirëse',
    'features.comprehensive.desc': '10 teste për kategori me pyetje të stilit të provimit real',
    'features.progress.title': 'Gjurmo Përparimin',
    'features.progress.desc': 'Analitika të avancuara për të monitoruar përmirësimin tënd',
    'features.guaranteed.title': 'Kalim i Garantuar',
    'features.guaranteed.desc': 'Metoda të provuara për të kaluar në përpjekjen e parë',

    // Materials Page (Albanian)
    'materials.title': 'Materiale mësimore',
    'materials.subtitle': 'Mëso teorinë e drejtimit hap pas hapi',
    'materials.searchPlaceholder': 'Kërko në këtë kapitull...',
    'materials.section.1': '1. Rregullat bazë të trafikut',
    'materials.section.2': '2. Futja në trafik & pozicionimi',
    'materials.section.3': '3. Rregullat e shpejtësisë',
    'materials.section.4': '4. Rregullat e kthimit',
    'materials.section.5': '5. Kryqëzimet',
    'materials.section.6': '6. Rrethrrotullimet',
    'materials.section.7': '7. Këmbësorët & çiklistët',
    'materials.section.8': '8. Takimi me trafik',
    'materials.section.9': '9. Parakalimi',
    'materials.section.10': '10. Kalo pengesat',
    'materials.section.11': '11. Sinjalet paralajmëruese',
    'materials.section.12': '12. Ndalimi & parkimi',
    'materials.section.13': '13. Defektet',
    'materials.readCarefully': 'Lexo me kujdes dhe lidh këto rregulla me situatat reale në trafik.',
    'materials.noResults': 'Asnjë rezultat nuk përputhet me kërkimin në këtë kapitull.',
    'materials.emptyTitle': 'Ende nuk ka materiale mësimore',
    'materials.emptySubtitle': 'Instruktori ose administratori yt ende nuk ka shtuar materiale për këtë kurs.',
    'materials.resultsForPrefix': 'Duke shfaqur rezultatet për',
    'materials.resultsForSuffix': 'në këtë kapitull',
    'materials.errorLoadFailed': 'Nuk u arrit të ngarkohen materialet',
    'materials.premiumRequiredTitle': 'Shkyç qasjen e plotë te materialet mësimore',
    'materials.premiumRequiredDescription': 'Materialet mësimore janë pjesë e planit të paguar. Me çdo plan aktiv ke qasje të plotë në të gjitha kapitujt, shpjegimet dhe figurat.',
    'materials.premiumBenefitAllChapters': 'Qasje në çdo kapitull dhe çdo shpjegim të temave.',
    'materials.premiumBenefitDeeper': 'Kupto pse përgjigjet janë të sakta që testet provuese të duken më të lehta.',
    'materials.premiumBenefitVisuals': 'Shiko të gjitha figurat dhe skemat për të memorizuar më shpejt.',
    'materials.premiumUpgradeCta': 'Shiko planet',

    // Categories
    'categories.title': 'Zgjidh Kategorinë e Patentës',
    'categories.description': 'Zgjidh llojin e patentës dhe fillo praktikën me testet tona gjithëpërfshirëse',
    'categories.startPractice': 'Fillo Praktikën',
    
    // Auth
    'auth.welcomeBack': 'Mirë se Erdhe Përsëri',
    'auth.signInDescription': 'Hyr për të vazhduar praktikën e teorisë së drejtimit',
    'auth.createAccount': 'Krijo Llogari',
    'auth.createAccountDescription': 'Fillo udhëtimin për të kaluar provimin e teorisë së drejtimit',
    'auth.email': 'Email',
    'auth.password': 'Fjalëkalimi',
    'auth.confirmPassword': 'Konfirmo Fjalëkalimin',
    'auth.fullName': 'Emri i Plotë',
    'auth.signIn': 'Hyr',
    'auth.signUp': 'Krijo Llogari',
    'auth.dontHaveAccount': 'Nuk ke llogari?',
    'auth.alreadyHaveAccount': 'Ke tashmë llogari?',
    'auth.backToHome': 'Kthehu në ballina',
    'auth.signingIn': 'Duke hyrë...',
    'auth.creatingAccount': 'Duke krijuar llogari...',
    'auth.logoutSuccess': 'U çkyçët me sukses.',
    'auth.logoutError': 'Gabim gjatë çkyçjes.',
    
    // Dashboard
    'dashboard.welcome': 'Mirë se erdhe përsëri',
    'dashboard.subtitle': 'Gjurmo përparimin dhe vazhdo të mësosh',
    'dashboard.totalTests': 'Teste Totale',
    'dashboard.avgScore': 'Rezultati Mesatar',
    'dashboard.bestScore': 'Rezultati më i Mirë',
    'dashboard.streak': 'Seria',
    'dashboard.thisWeek': 'këtë javë',
    'dashboard.lastWeek': 'javën e kaluar',
    'dashboard.personalBest': 'Rekord personal',
    'dashboard.keepGoing': 'Vazhdo kështu!',
    'dashboard.streakSubtitle': 'Seri ditore në të gjitha aktivitetet (teste dhe Decision Trainer).',
    'dashboard.days': 'ditë',
    'dashboard.weeklyProgress': 'Përparimi Javor',
    'dashboard.weeklyProgressDesc': 'Rezultatet e testeve gjatë javës së kaluar',
    'dashboard.passRate': 'Shkalla e Kalimit',
    'dashboard.passRateDesc': 'Performanca e përgjithshme',
    'dashboard.categoryPerformance': 'Performanca sipas Kategorisë',
    'dashboard.categoryPerformanceDesc': 'Teste për kategori',
    'dashboard.recentTests': 'Testet e Fundit',
    'dashboard.recentTestsDesc': 'Përpjekjet e fundit',
    'dashboard.continuelearning': 'Vazhdo Mësimin',
    'dashboard.pickUpWhere': 'Vazhdo nga ku e le',
    'dashboard.continueCategoryB': 'Vazhdo Kategorinë B',
    'dashboard.browseCategories': 'Shfleto Kategoritë',
    'dashboard.startNewCategory': 'Fillo Kategori të Re',
    'dashboard.passed': 'Kaluar',
    'dashboard.failed': 'Dështuar',
    'dashboard.weakTopicsTitle': 'Temat e tua më të dobëta',
    'dashboard.weakTopicsSubtitle': 'Këto janë temat ku gabon më shpesh në të gjitha testet.',
    'dashboard.testAchievementsTitle': 'Arritjet në testet teorike',
    'dashboard.testAchievementsSubtitle': 'Objektiva të vegjël për të të motivuar gjatë praktikës me teste.',
    'dashboard.trainerProgressTitle': 'Përparimi në Decision Trainer',
    'dashboard.trainerAchievementsLabel': 'Arritjet:',
    'dashboard.trainerScenarios': 'skenarë',
    'dashboard.trainerAccuracy': 'saktësi',
    'dashboard.trainerXp': 'XP',
    'dashboard.trainerBestStreak': 'Seria më e mirë',
    'dashboard.trainerCategoriesPracticed': 'Kategoritë e praktikuara',
    'dashboard.testHistoryTitle': 'Historia e testeve',
    'dashboard.testHistorySubtitle': 'Shiko të gjitha testet e përfunduara dhe rishiko përgjigjet',
    'dashboard.viewHistoryCta': 'Shiko historinë',
    'dashboard.avgScoreHighSubtitle': 'Shumë mirë!',
    'dashboard.avgScoreLowSubtitle': 'Vazhdo praktikën',
    'profile.title': 'Përmbledhje e planit dhe përdorimit',
    'profile.adminUnlimited': 'Admin: Ke tashmë qasje të pakufizuar në të gjitha kategoritë dhe funksionet.',
    'profile.premiumBadge': 'Plan i paguar aktiv',
    'profile.planStatusTitle': 'Planet dhe përdorimi sipas kategorisë së patentës',
    'profile.expiresOnLabel': 'Skadon më:',
    'profile.daysRemaining': 'ditë të mbetura',
    'profile.freeUsageLabel': 'Përdorimi falas këtë cikël:',
    'profile.testsLabel': 'teste',
    'profile.upgradeCta': 'Fillo planin',
    'profile.extendCta': 'Zgjat / rinovo',
    'profile.previewCta': 'Menaxho përdoruesit',
    'profile.accountSettingsTitle': 'Cilësimet e llogarisë',
    'profile.accountSettingsDescription': 'Përditëso emrin e shfaqur dhe shiko cili email përdoret për llogarinë tënde DriveWise.',
    'profile.displayNameLabel': 'Emri i shfaqur',
    'profile.emailLabel': 'Email',
    'profile.emailHelp': 'Ky email përdoret për hyrje dhe njoftime të rëndësishme të llogarisë.',
    'profile.dangerZoneTitle': 'Zonë e rrezikshme',
    'profile.dangerZoneDescription': 'Fshij përgjithmonë llogarinë dhe të gjitha të dhënat, përfshirë historinë e testeve, progresin në Decision Trainer dhe planet.',
    'profile.deleteAccountButton': 'Fshij llogarinë',
    'profile.deleteDialogTitle': 'Fshij llogarinë',
    'profile.deleteDialogDescription': 'Kjo veprim nuk mund të zhbëhet. Llogaria jote DriveWise dhe të gjitha të dhënat do të fshihen përgjithmonë, përfshirë historinë e testeve, progresin në Decision Trainer dhe çdo plan aktiv ose të kaluar.',
    'profile.deleteDialogConfirmLabel': 'Shkruaj DELETE me shkronja të mëdha për të konfirmuar:',
    'profile.deleteDialogCancel': 'Anulo',
    'profile.deleteDialogConfirm': 'Fshij llogarinë time',
    'profile.deleteDialogConfirming': 'Duke fshirë...',

    // Dashboard Onboarding / Learning Path (Albanian)
    'dashboard.onboardingTitle': 'Fillo udhëtimin tënd të mësimit',
    'dashboard.onboardingSubtitle': 'Ndiqi këto tre hapa për t’u përgatitur për provimin e teorisë.',
    'dashboard.onboardingStep1': '1. Lexo materialet mësimore për kapitullin e radhës.',
    'dashboard.onboardingStep2': '2. Praktiko situata reale në Decision Trainer.',
    'dashboard.onboardingStep3': '3. Testo veten me teste të plota provuese.',
    
    // Decision Trainer Page (Albanian)
    'trainer.title': 'Decision Trainer',
    'trainer.practiceModes': 'Mënyrat e praktikës',
    'trainer.fullCategory': 'E gjithë kategoria',
    'trainer.quick5': 'Shpejt: 5 pyetje',
    'trainer.quick10': 'Shpejt: 10 pyetje',
    'trainer.weakPoints': 'Pikat e dobëta',
    'trainer.statusNew': 'E re',
    'trainer.statusStrong': 'I/e fortë',
    'trainer.statusImproving': 'Në përmirësim',
    'trainer.statusNeedsAttention': 'Kërkon vëmendje',
    'trainer.lastSessionTitle': 'Seanca e fundit',
    'trainer.questionsToReview': 'Pyetje për t’u rishikuar:',
    'trainer.perfectSession': 'Seancë perfekte! Nuk ka gabime për t’u rishikuar.',
    'trainer.practiceAgain5': 'Praktiko përsëri këtë kategori (5 pyetje)',
    'trainer.leaderboard': 'Tabela e rezultateve',
    'trainer.toastTimesUp': 'Koha mbaroi!',
    'trainer.toastCorrect': 'Saktë!',
    'trainer.toastIncorrect': 'Gabim. Lexo shpjegimin për të mësuar.',
    'trainer.toastWeakLocked': 'Përfundo të paktën një kategori që të hapet mënyra e pikave të dobëta.',
    'trainer.toastFocusingWeak': 'Po fokusohemi te kategoria jote më e dobët:',
    'trainer.toastSyncFailed': 'Rezultatet u ruajtën lokalisht por nuk u sinkronizuan me tabelën.',
    'trainer.modeFull': 'E gjithë kategoria',
    'trainer.modeQuick5': 'Shpejt: 5 pyetje',
    'trainer.modeQuick10': 'Shpejt: 10 pyetje',
    'trainer.modeWeak': 'Pikat e dobëta (5 pyetje)',
    'trainer.scenariosShort': 'skenarë',
    'trainer.accuracyShort': 'saktësi',
    'trainer.premiumRequiredTitle': 'Shkyç Decision Trainer',
    'trainer.premiumRequiredDescription': 'Decision Trainer është pjesë e planit të paguar. Me çdo plan aktiv ke qasje të plotë në të gjitha skenarët, mënyrat e zgjuara të praktikës dhe rishikimet e detajuara.',
    'trainer.premiumBenefitUnlimited': 'Praktikë e pakufizuar në Decision Trainer për të gjitha kategoritë.',
    'trainer.premiumBenefitStudy': 'Lidh skenarët me kapitujt përkatës dhe rishikimin e testeve.',
    'trainer.premiumBenefitFocus': 'Mënyra të zgjuara që fokusohen te pikat e dobëta dhe koha.',
    'trainer.premiumUpgradeCta': 'Shiko planet',

    // Category Page
    'category.licenseCategory': 'Kategoria e Patentës',
    'category.mockTests': 'Teste Provuese',
    'category.minutesEach': 'minuta secila',
    'category.selectTest': 'Zgjidh Testin Tënd',
    'category.selectTestDesc': 'Zgjidh nga 10 teste gjithëpërfshirëse',
    'category.questions': 'Pyetje',
    'category.start': 'Fillo',
    'category.noTestsTitle': 'Ende nuk ka teste',
    'category.noTestsDescription': 'Instruktori ose administratori yt nuk ka shtuar ende teste provuese për këtë kategori.',
    
    // Test Page
    'test.exitTest': 'Dil nga Testi',
    'test.question': 'Pyetja',
    'test.of': 'nga',
    'test.backToTests': 'Kthehu te Testet',
    'test.congratulations': 'Urime!',
    'test.keepPracticing': 'Vazhdo të Praktikosh!',
    'test.test': 'Testi',
    'test.correctAnswers': 'përgjigje të sakta',
    'test.passingScore': 'Rezultati për Kalim',
    'test.passed': 'Kaluar',
    'test.failed': 'Dështuar',
    'test.retakeTest': 'Ri-bëj Testin',
    'test.viewAllTests': 'Shiko të Gjitha Testet',
    'test.loadingQuestions': 'Duke ngarkuar pyetjet e testit...',
    'test.noQuestionsTitle': 'Nuk ka pyetje',
    'test.noQuestionsDescription': 'Nuk ka ende pyetje të disponueshme për këtë test.',
    'test.sessionStats': 'Statistikat e sesionit',
    'test.correctLabel': 'Të sakta',
    'test.accuracy': 'Saktësia',
    'test.bestStreak': 'Seria më e mirë',
    'test.selectAnswers': 'Zgjidh një ose më shumë përgjigje',
    'test.optionsSelected': 'opsione të zgjedhura',
    'test.mixedName': 'Test me pyetje të përziera',
    'test.personalizedName': 'Test i personalizuar',
    'test.previous': 'Mbrapa',
    'test.next': 'Tjetra',
    'test.submitTest': 'Dorëzo Testin',
    'test.submitAnswer': 'Dorëzo përgjigjen',
    'test.timeLeft': 'Koha e mbetur',
    'test.questionImage': 'Imazhi i pyetjes',
    'test.questionIllustration': 'Ilustrimi i pyetjes',
    'test.answeredLabel': 'të përgjigjura',
    'test.correctTitle': '✓ E saktë!',
    'test.incorrectTitle': '✗ E pasaktë - mëso nga kjo!',
    'test.nextStepsTitle': 'Çfarë duhet të bësh më pas?',
    'test.nextStepsPassedStandard': 'Shumë mirë! Tani provo një test të përzier ose vazhdo në Decision Trainer për të thelluar njohuritë.',
    'test.nextStepsPassedMixedOrPersonalized': 'Shumë mirë! Mund të vazhdosh me më shumë teste në këtë kategori ose me Decision Trainer.',
    'test.nextStepsFailedPersonalized': 'Rishiko këtë test të personalizuar për të kuptuar gabimet dhe më pas fokusoju në pikat e dobëta në Decision Trainer.',
    'test.nextStepsFailedStandard': 'Rishiko me kujdes këtë test, pastaj provo një test të personalizuar dhe Decision Trainer për t’u fokusuar në pikat e dobëta.',
    'test.practiceWeakPointsCta': 'Praktiko pikat e dobëta',
    'test.mixedTestCta': 'Test i përzier për këtë kategori',
    'test.decisionTrainerCta': 'Decision Trainer',
    'test.weakTopicsInThisTest': 'Tema të dobëta në këtë test',

    // History / Review Page (Albanian)
    'history.reviewSubtitle': 'Rishiko përgjigjet dhe mëso nga gabimet',
    'history.topicsTitle': 'Temat në këtë test',
    'history.topicsSubtitle': 'Shiko ku je i/e fortë dhe ku duhet të përqendrohesh.',
    'history.weakTopicsPrefix': 'Tema të dobëta:',
    'history.explanationTitle': 'Shpjegimi',
    'history.notFoundTitle': 'Testi nuk u gjet',
    'history.notFoundDescription': 'Ky test nuk mund të gjendet ose është fshirë.',
    'history.missingQuestionTitle': 'Të dhënat e pyetjes mungojnë',
    'history.backToHistory': 'Kthehu te historia',

    // Error Page (Albanian)
    'error.title': 'Ups! Diçka shkoi keq',
    'error.message': 'Pati një gabim të papritur. Nuk është faji yt dhe të dhënat e tua janë të sigurta. Provo përsëri ose kthehu te paneli.',
    'error.tryAgain': 'Provo përsëri',
    'error.goToDashboard': 'Shko te paneli',
    'error.needHelp': 'Kërkon ndihmë?',
    'error.contactSupport': 'Nëse problemi përsëritet, kontakto mbështetjen duke i treguar kohën kur ndodhi gabimi.',

    // Achievements (Albanian)
    'achievements.firstTestTitle': 'Testi i parë i përfunduar',
    'achievements.firstTestDesc': 'Përfundo testin tënd të parë provues të teorisë.',
    'achievements.fivePassesRowTitle': 'Në seri fituese',
    'achievements.fivePassesRowDesc': 'Kalo 5 teste teorike radhazi me të paktën 80% rezultat.',
    'achievements.hundredQuestionsTitle': '100 pyetje të përgjigjura',
    'achievements.hundredQuestionsDesc': 'Përgjigju të paktën 100 pyetjeve të teorisë në të gjitha testet.',

    // Decision Trainer Next Steps (Albanian)
    'trainer.nextStepsTitle': 'Çfarë duhet të bësh më pas?',
    'trainer.nextStepsHigh': 'Saktësi shumë e mirë në këtë kategori. Tani mund ta sfidosh veten me një test të plotë ose një test të përzier.',
    'trainer.nextStepsMedium': 'Përparim i mirë, por ka ende hapësirë për përmirësim. Praktiko edhe disa skenarë dhe më pas provo një test teorik në këtë kategori.',
    'trainer.nextStepsLow': 'Fokusoju në kuptimin e shpjegimeve dhe rishiko kapitujt përkatës, pastaj vazhdo praktikën në Decision Trainer para se të bësh një test të plotë.',
    'trainer.goToTestsCta': 'Shko te testet për këtë kategori',
    'trainer.practiceMoreCta': 'Praktiko më shumë skenarë',
    'trainer.weakPointsModeCta': 'Fokusoju në pikat e dobëta',
    'trainer.reviewMaterialsCta': 'Rishiko materialet përkatëse',
    'trainer.firstSteps': 'Hapat e parë',
    'trainer.accuracyAce': 'Kampion i saktësisë',
    'trainer.streakMaster': 'Mjeshtër i serive',
    'trainer.xpHunter': 'Gjuetari i XP-së',
    'trainer.categoryExplorer': 'Eksplorues kategorish',
    'trainer.noScenariosTitle': 'Ende nuk ka skenarë',
    'trainer.noScenariosSubtitle': 'Kërko nga instruktori ose administratori yt të shtojë skenarë në Decision Trainer.',
    'trainer.firstScenarioDesc': 'Përfundo skenarin tënd të parë në Decision Trainer.',
    'trainer.accuracyAceDesc': 'Arrij të paktën 80% saktësi në të paktën 20 përpjekje.',
    'trainer.streakMasterDesc': 'Arrij një seri prej 10 përgjigjesh të sakta radhazi.',
    'trainer.xpHunterDesc': 'Fito gjithsej 500 XP në Decision Trainer.',
    'trainer.categoryExplorerDesc': 'Praktiko të paktën 3 kategori të ndryshme në Decision Trainer.',
    'trainer.consistencyPro': 'I qëndrueshëm',
    'trainer.consistencyProDesc': 'Përfundo të paktën 50 skenarë në Decision Trainer në të gjitha kategoritë.',
    'trainer.achievementsUnlockedLabel': 'të hapura',
    'trainer.correctCombinationLabel': 'Kombinimi i saktë:',
    'trainer.yourSelectionLabel': 'Zgjedhja jote:',
    'trainer.noSelectionLabel': 'Nuk është zgjedhur asnjë opsion',
    'trainer.reviewChapterCta': 'Rishiko kapitullin',
    
    // Leaderboard (Albanian)
    'leaderboard.backToTrainer': 'Kthehu te Decision Trainer',
    'leaderboard.subtitle': 'Nxënësit më të mirë në Decision Trainer',
    'leaderboard.noDataTitle': 'Ende nuk ka të dhëna në tabelë',
    'leaderboard.noDataSubtitle': 'Përfundo disa skenarë në Decision Trainer që të shfaqesh në tabelën e rezultateve!',
    'leaderboard.startLearningCta': 'Fillo mësimin',
    'leaderboard.top10Title': 'Top 10 tabela',
    'leaderboard.showingTop10Of': 'Duke shfaqur top 10 nga',
    'leaderboard.highestXp': 'XP më i lartë',
    'leaderboard.topAccuracy': 'Saktësia më e mirë',
    'leaderboard.longestStreak': 'Seria më e gjatë',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Start with a stable default for SSR and first client render to avoid hydration mismatches
  const [language, setLanguageState] = useState<Language>('en');

  // After mount, read the persisted language from localStorage (client-only)
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const savedLanguage = localStorage.getItem('language') as Language | null;
    if (savedLanguage === 'sq' || savedLanguage === 'en') {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t
  }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
